model_name: 'lasso_cv'

model_output_paths:
  dir: 'models'
  model: 'lasso_cv.joblib'
  pipeline: 'lasso_cv_pipeline.joblib'

preprocessing:
  test_size: 0.2
  eval_size: 0.15
  variance_threshold: 0.01
  logspace:
    start: -3
    end: 3
    num: 100
  cv: 5